services:
  db:
    image: postgres:15
    container_name: postgres_cont
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user_order_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  back-image:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back_cont
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user_order_db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: